<?php

return [
	'name' => 'CoffeeScript',
	'vendor' => 'Jeremy Ashkenas',
	'version' => function() {
		$jsLatest = file_get_contents('https://raw.githubusercontent.com/jashkenas/coffeescript/master/lib/coffee-script/coffee-script.js');

		if ($jsLatest) {
			$jsLatest = str_replace("\n", '', $jsLatest);

			if (preg_match('/Generated by CoffeeScript (\d{1,2}\.\d{1,2}\.\d{1,2})/i', $jsLatest, $matches)) {
				return $matches[1];
			}
		}

		return false;
	}
];
